language: node_js
node_js:
  - 12

services:
  - docker

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker build -t yoonseokch/ict-backend:${TRAVIS_TAG} .;
    else
      docker build -t yoonseokch/ict-backend:latest .;
    fi

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PW"
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker push yoonseokch/ict-backend:${TRAVIS_TAG};
    else
      docker push yoonseokch/ict-backend:latest;
    fi

